# Define artifacts root directory
artifacts_root: artifacts

# Define data ingestion parameters
data_ingestion:
  # Define root directory for data ingestion
  root_dir: artifacts/data_ingestion
  # Define source URL for the data
  source_URL: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing
  # Define local path for the downloaded data file
  local_data_file: artifacts/data_ingestion/data.zip
  # Define directory for unzipping the data
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras
